https://mp.weixin.qq.com/s?__biz=MzIyNjM2MzQyNg==&mid=2247488351&idx=1&sn=44421aeaaa7ce1aa49208b211a03140a&chksm=e870c212df074b04b42825e6a427a2e2645bddb82754eeabedf97f8e5d25135280bad2052278&mpshare=1&scene=1&srcid=&sharer_sharetime=1579083946268&sharer_shareid=8724c7983f20914ec3c0c086bba89335&key=1dba98cf68729bcfba254e2a69fa2e7589b973dc40cae34b922bcf6032ccc76918b21e65084fb09e83497dfb45268bbd9db99449bab09d53b70e9484d61199e12581a5da99fd62fc80faefe88064eb60&ascene=1&uin=MjA1MjAyODkxNg%3D%3D&devicetype=Windows+10&version=6208006f&lang=zh_CN&exportkey=AQqAzavKVHLKgYFctihBIec%3D&pass_ticket=W0v45PKV4JSO%2FtG2mcuX6wMt5Uy25arZ62TddyVZKGIfuGGw1xy3riFWBpz2iJL0

In [1]:
import torch

In [2]:
# 2.创建一个空的5*3张量
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 3.创建一个随机初始化的5*3张量
x = torch.rand(5,3)
print(x)

tensor([[0.3452, 0.0665, 0.3460],
        [0.0758, 0.6418, 0.8582],
        [0.3455, 0.4442, 0.2645],
        [0.0820, 0.7413, 0.7932],
        [0.1285, 0.0522, 0.2280]])


In [4]:
# 4.创建一个5x3的0张量，类型为long
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 5.直接从数组创建张量
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 6.创建一个5x3的单位张量，类型为double
x = torch.ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# 7.从已有的张量创建相同维度的新张量，并且重新定义类型为float
x = torch.rand_like(x,dtype=torch.float)
print(x)

tensor([[0.5941, 0.6370, 0.4928],
        [0.7551, 0.0272, 0.9159],
        [0.3898, 0.4157, 0.5357],
        [0.0933, 0.8540, 0.6426],
        [0.3260, 0.5462, 0.0697]])


In [8]:
# 8.打印一个张量的维度
print(x.size())

torch.Size([5, 3])


In [9]:
# 9.将两个张量相加
y = torch.rand(5,3)
print(x + y)
# 方法二
# print(torch.add(x, y))

# 方法三
# result = torch.empty(5, 3)
# torch.add(x, y, out=result)
# print(result)

# 方法四
# y.add_(x)
# print(y)

tensor([[1.3222, 0.7850, 0.5372],
        [1.6780, 0.2707, 1.3160],
        [1.0906, 0.9106, 0.9166],
        [0.1965, 1.7770, 0.7219],
        [0.6225, 0.9395, 0.7210]])


In [10]:
# 10.取张量的第一列
print(x[:,0])

tensor([0.5941, 0.7551, 0.3898, 0.0933, 0.3260])


In [11]:
# 11.将一个4x4的张量resize成一个一维张量
x = torch.rand(4,4)
y = x.view(16)
print(x.size(),y.size())

torch.Size([4, 4]) torch.Size([16])


In [12]:
# 12.将一个4x4的张量，resize成一个2x8的张量
y = x.view(2, 8)
print(x.size(),y.size())

# 方法二
z = x.view(-1, 8) # 确定一个维度，-1的维度会被自动计算
print(x.size(),z.size())

torch.Size([4, 4]) torch.Size([2, 8])
torch.Size([4, 4]) torch.Size([2, 8])


In [13]:
# 13.从张量中取出数字
x = torch.randn(1)
print(x.item())

-0.09322551637887955


In [14]:
# 14.将张量转换成numpy数组
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
# 15.将张量+1，并观察上题中numpy数组的变化
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
# 16.从numpy数组创建张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
# 17.将numpy数组+1并观察上题中张量的变化
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### 2.自动微分
##### 2.1 张量的自动微分

In [18]:
# 18.新建一个张量，并设置requires_grad=True
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
# 19.对张量进行任意操作（y = x + 2）
y = x + 2
print(y)
print(y.grad_fn) # y就多了一个AddBackward

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [20]:
# 20.再对y进行任意操作
z = y * y * 3
out = z.mean()
print(z) # z多了MulBackward
print(out) # out多了MeanBackward

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


##### 2.2 梯度

In [21]:
# 21.对out进行反向传播
out.backward()

In [22]:
# 22.打印梯度d(out)/dx
print(x.grad) # out=0.25*Σ3(x+2)^2

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [23]:
# 23.创建一个结果为矢量的计算过程（y=x*2^n）
x = torch.randn(3,requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -552.8284,  -150.5768, -1231.4563], grad_fn=<MulBackward0>)


In [24]:
# 24.计算v = [0.1, 1.0, 0.0001]处的梯度
v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [25]:
# 25.关闭梯度的功能
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)
# 方法二
# print(x.requires_grad)
# y = x.detach()
# print(y.requires_grad)
# print(x.eq(y).all())

True
True
False


#### 3. 神经网络

In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        # 26.定义①的卷积层，输入为32×32的图像，卷积核大小5×5卷积核种类6
        self.conv1 = nn.Conv2d(3,6,5)
        # 27.定义③的卷积层，输入为前一层6个特征，卷积核大小5x5，卷积核种类16
        self.conv2 = nn.Conv2d(6,16,5)
        # 28.定义⑤的全链接层，输入为16*5*5，输出为120
        self.fc1 = nn.Linear(16*5*5,120) # 6*6 from image dimension
        # 29.定义⑥的全连接层，输入为120，输出为84
        self.fc2 = nn.Linear(120,84)
        # 30.定义⑥的全连接层，输入为84，输出为10
        self.fc3 = nn.Linear(84,10)
    def forward(self,x):
        # 31.完成input-S2，先卷积+relu，再2x2下采样
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        