In [1]:
import numpy as np
import torch

In [2]:
# Input
inputs = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                  [69,96,70]],dtype='float32')

In [3]:
# Targets
targets = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119]],dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
print(inputs,targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
# weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.2327,  1.3877,  1.0904],
        [-1.8799,  1.3272, -0.1196]], requires_grad=True)
tensor([-0.2381,  1.7320], requires_grad=True)


In [7]:
def model(x):
    return x @ w.t() + b

In [8]:
preds = model(inputs)
print(preds)

tensor([[ 122.6355,  -51.7184],
        [ 170.4866,  -60.1956],
        [ 228.7073,    9.0946],
        [  76.0400, -137.3729],
        [ 193.2505,   -8.9365]], grad_fn=<AddBackward0>)


In [9]:
# MSE LOSS
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff) /diff.numel() # numel返回数组中的个数
# compute loss
loss = mse(preds,targets)
print(loss)

tensor(13847.4893, grad_fn=<DivBackward0>)


In [10]:
# 计算梯度  因为requires_grad被设置为True，Pytorch自动计算损耗的梯度，权重和偏差
loss.backward()

In [11]:
print(w)
print(w.grad)

tensor([[-0.2327,  1.3877,  1.0904],
        [-1.8799,  1.3272, -0.1196]], requires_grad=True)
tensor([[  6858.3145,   7605.5903,   4654.5020],
        [-12189.5312, -11744.7207,  -7628.8545]])


In [12]:
# 重置梯度
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [14]:
# 使用梯度下降调整权重和偏差
preds = model(inputs)
print(preds)

tensor([[ 122.6355,  -51.7184],
        [ 170.4866,  -60.1956],
        [ 228.7073,    9.0946],
        [  76.0400, -137.3729],
        [ 193.2505,   -8.9365]], grad_fn=<AddBackward0>)


In [15]:
loss = mse(preds,targets)
print(loss)

tensor(13847.4893, grad_fn=<DivBackward0>)


In [22]:
type(loss)

torch.Tensor

In [16]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  6858.3145,   7605.5903,   4654.5020],
        [-12189.5312, -11744.7207,  -7628.8545]])
tensor([  82.0240, -141.8257])


In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [18]:
print(w)
print(b)

tensor([[-0.3013,  1.3116,  1.0439],
        [-1.7580,  1.4447, -0.0433]], requires_grad=True)
tensor([-0.2389,  1.7334], requires_grad=True)


In [19]:
# 再看看损失
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(9555.8145, grad_fn=<DivBackward0>)


In [20]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [21]:
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(211.7212, grad_fn=<DivBackward0>)
