In [1]:
import torch
import torchvision

In [2]:
# Vector
t2 = torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [3]:
# Matrix
t3 = torch.tensor([[5,6],[7,8],[9,10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [4]:
# 3-dimensional arrary
t4 = torch.tensor([
    [[11,12,13],[13,14,15]],
    [[15,16,17],[17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [7]:
# Numpy的数组和Pytorch数组之间进行转换
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [8]:
# 转换numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [2]:
# import jovian
# jovian.commit()

In [3]:
# Indexing,Splicing and Joining

In [4]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 0.2976,  1.0142, -1.2587,  0.0805],
        [ 0.8170, -0.6393,  0.9111, -0.3503],
        [ 0.6746, -2.0584,  0.8207, -0.5312]])
x[:1]: 
tensor([[ 0.2976,  1.0142, -1.2587,  0.0805]])
x[:1, 1:3]: 
tensor([[ 1.0142, -1.2587]])


In [7]:
# Select with dimensional indicies
x = torch.randn(2,3)
print("values:\n{}".format(x))
col_indices = torch.LongTensor([0,2])
# print(col_indices)
chosen = torch.index_select(x,dim=1,index=col_indices)
print("Values: \n{}".format(chosen))
row_indices = torch.LongTensor([0,1])
chosen = x[row_indices,col_indices]
print("Values: \n{}".format(chosen))

values:
tensor([[ 0.0387,  1.4353,  0.3322],
        [-1.7796, -1.4772,  0.1130]])
Values: 
tensor([[ 0.0387,  0.3322],
        [-1.7796,  0.1130]])
Values: 
tensor([0.0387, 0.1130])


In [8]:
# Concatenation
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print("Values: \n{}".format(y))

Values: 
tensor([[-0.0138, -1.0251,  0.9335],
        [-1.0779,  0.2411,  0.1354]])
Values: 
tensor([[-0.0138, -1.0251,  0.9335],
        [-1.0779,  0.2411,  0.1354],
        [-0.0138, -1.0251,  0.9335],
        [-1.0779,  0.2411,  0.1354]])


In [9]:
# Gradients
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()  # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.7549, 0.8963, 0.6524, 0.0094],
        [0.8066, 0.9328, 0.9037, 0.7160],
        [0.4034, 0.3022, 0.6138, 0.9105]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [10]:
# CUDA tensors
# Is CUDA available?
print(torch.cuda.is_available())

True


In [11]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [12]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
