In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape(2,3)
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array',np_data,
    '\ntorch tensor',torch_data,
    '\ntensor to array',tensor2array
)


numpy array [[0 1 2]
 [3 4 5]] 
torch tensor tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor to array [[0 1 2]
 [3 4 5]]


In [3]:
# torch中的数学运算
data = [-1,-2,1,2]
tensor = torch.FloatTensor(data)
print(np.abs(data))
print(torch.abs(tensor))

[1 2 1 2]
tensor([1., 2., 1., 2.])


In [4]:
# 变量Variable
from torch.autograd import Variable

In [5]:
tensor = torch.FloatTensor([[1,2],[3,4]])
variable = Variable(tensor,requires_grad=True)
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
# Variable计算梯度
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [7]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [8]:
# 获取Variable里面的数据
print(variable) # Variable形式
print(variable.data) # tensor形式
print(variable.data.numpy()) # numpy形式

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]


In [10]:
# Torch中的激活函数
import torch
from torch.autograd import Variable
import torch.nn.functional as F