In [1]:
import torch
import torchvision

In [2]:
# Vector
t2 = torch.tensor([1,2,3,4])
t2

tensor([1, 2, 3, 4])

In [3]:
# Matrix
t3 = torch.tensor([[5,6],[7,8],[9,10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [4]:
# 3-dimensional arrary
t4 = torch.tensor([
    [[11,12,13],[13,14,15]],
    [[15,16,17],[17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [7]:
# Numpy的数组和Pytorch数组之间进行转换
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [8]:
# 转换numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [ ]:
import jovian
jovian.commit()