In [7]:
import torch.nn as nn
import numpy as np
import torch

In [4]:
# Input
inputs = np.array([[73,67,43],
                  [91,88,64],
                  [87,134,58],
                  [102,43,37],
                  [69,96,70]],dtype='float32')
# Targets
targets = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119]],dtype='float32')

In [8]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [9]:
# 创建一个tensorDataset和一个DataLoader
from torch.utils.data import TensorDataset

In [10]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [11]:
from torch.utils.data import DataLoader

In [12]:
# 定义数据加载器
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [13]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 87., 134.,  58.],
        [ 91.,  88.,  64.]])
tensor([[ 56.,  70.],
        [ 22.,  37.],
        [103., 119.],
        [119., 133.],
        [ 81., 101.]])


In [14]:
# 用nn.Linear自动初始化
#定义模型
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5400, -0.5225, -0.4104],
        [ 0.2868, -0.3981, -0.0993]], requires_grad=True)
Parameter containing:
tensor([-0.0196,  0.0652], requires_grad=True)


In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.5400, -0.5225, -0.4104],
         [ 0.2868, -0.3981, -0.0993]], requires_grad=True),
 Parameter containing:
 tensor([-0.0196,  0.0652], requires_grad=True)]

In [17]:
# 内置损失函数mse_loss
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(26107.8652, grad_fn=<MseLossBackward>)


In [18]:
# 定义优化器
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [19]:
def fit(num_epochs,model,loss_fn,opt):
    for epoch in range(num_epochs):
        for xb,yb in train_dl:
            preds = model(xb)
            loss = loss_fn(preds,yb)
            loss.backward()
            # 用梯度更新参数
            opt.step()
            # 重置参数为0
            opt.zero_grad()
        if (epoch + 1) % 10 == 0:
            print('Epoch[{}/{}],Loss:{:.4f}'.format(epoch + 1,num_epochs,loss.item()))

In [20]:
fit(100,model,loss_fn,opt)

Epoch[10/100],Loss:1447.9030
Epoch[20/100],Loss:653.4196
Epoch[30/100],Loss:566.2062
Epoch[40/100],Loss:501.1792
Epoch[50/100],Loss:444.0906
Epoch[60/100],Loss:393.7699
Epoch[70/100],Loss:349.4059
Epoch[80/100],Loss:310.2888
Epoch[90/100],Loss:275.7930
Epoch[100/100],Loss:245.3682
